spring:
    datasource:
#        url: jdbc:h2:file:./build/db/authaudit-dev;DB_CLOSE_DELAY=-1
        url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driver-class-name: org.h2.Driver
        platform: h2
    jpa:
        database: H2
        show-sql: true
        hibernate:
            ddl-auto: none
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml
